"""
Render a compliance report to a one-page PDF with ReportLab.

Kept dependency-light and self-contained: no HTML/CSS engine, just the platypus
document model. Returns raw bytes for a ``StreamingResponse``.
"""

from __future__ import annotations

import io

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.models.report import Report
from app.models.store import Store

_BRAND = colors.HexColor("#1f5bff")
_VIOLET = colors.HexColor("#7c5cff")
_MUTED = colors.HexColor("#5b6478")


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "fg-title", parent=base["Title"], fontSize=20, textColor=_BRAND, spaceAfter=2
        ),
        "eyebrow": ParagraphStyle(
            "fg-eyebrow", parent=base["Normal"], fontSize=8, textColor=_MUTED, spaceAfter=10
        ),
        "h2": ParagraphStyle(
            "fg-h2",
            parent=base["Heading2"],
            fontSize=12,
            textColor=_VIOLET,
            spaceBefore=14,
            spaceAfter=4,
        ),
        "body": ParagraphStyle(
            "fg-body", parent=base["Normal"], fontSize=9.5, leading=14, alignment=TA_LEFT
        ),
        "small": ParagraphStyle("fg-small", parent=base["Normal"], fontSize=8, textColor=_MUTED),
    }


def render_report_pdf(report: Report, store: Store) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title=f"FranchiseGuard Compliance Report {report.reference}",
        author="FranchiseGuard AI",
    )
    st = _styles()
    flow: list = []

    flow.append(Paragraph("FranchiseGuard AI — Compliance Report", st["title"]))
    flow.append(
        Paragraph(
            f"{report.reference} &nbsp;·&nbsp; generated {report.generated_at:%Y-%m-%d %H:%M UTC} "
            f"&nbsp;·&nbsp; status {report.status.value.upper()}",
            st["eyebrow"],
        )
    )
    flow.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e5e8f0")))

    summary_rows = [
        ["Store", f"{store.name}  ({store.code})"],
        ["Region", store.region],
        ["Inspector", report.inspector_name or "—"],
        ["Model", report.model_version or "—"],
        ["Risk score", f"{report.risk_score} / 100  ({report.risk_level.value})"],
        ["Grade", report.grade],
        [
            "Findings",
            f"{report.critical_count} critical · {report.major_count} major · {report.minor_count} minor",
        ],
    ]
    table = Table(summary_rows, colWidths=[32 * mm, None])
    table.setStyle(
        TableStyle(
            [
                ("FONTSIZE", (0, 0), (-1, -1), 9.5),
                ("TEXTCOLOR", (0, 0), (0, -1), _MUTED),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("LINEBELOW", (0, 0), (-1, -2), 0.4, colors.HexColor("#eef0f6")),
            ]
        )
    )
    flow.append(Spacer(1, 8))
    flow.append(table)

    flow.append(Paragraph("Summary", st["h2"]))
    flow.append(Paragraph(report.summary, st["body"]))

    if report.recommendations:
        flow.append(Paragraph("Recommendations", st["h2"]))
        for rec in report.recommendations:
            flow.append(
                Paragraph(
                    f"<b>[{str(rec.get('priority', '')).upper()}] {rec.get('title', '')}</b> "
                    f"— {rec.get('detail', '')} <i>({rec.get('owner', '')})</i>",
                    st["body"],
                )
            )
            flow.append(Spacer(1, 3))

    if report.timeline:
        flow.append(Paragraph("Timeline", st["h2"]))
        for ev in report.timeline:
            flow.append(
                Paragraph(
                    f"<b>{ev.get('time', '')}</b> — {ev.get('title', '')}: {ev.get('detail', '')}",
                    st["body"],
                )
            )
            flow.append(Spacer(1, 2))

    flow.append(Spacer(1, 16))
    flow.append(
        Paragraph(
            "Generated by FranchiseGuard AI. Findings produced by an automated vision model and "
            "are advisory; confirm on site before enforcement action.",
            st["small"],
        )
    )

    doc.build(flow)
    return buf.getvalue()
