"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-29 13:21:08.952907

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=160), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "ADMIN",
                "AREA_MANAGER",
                "INSPECTOR",
                "FRANCHISE_OWNER",
                name="userrole",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("region", sa.String(length=80), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("external_subject", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_users_external_subject"), ["external_subject"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_users_region"), ["region"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_role"), ["role"], unique=False)

    op.create_table(
        "stores",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=24), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("brand", sa.String(length=80), nullable=False),
        sa.Column("region", sa.String(length=80), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("country", sa.String(length=80), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "ONBOARDING",
                "SUSPENDED",
                "CLOSED",
                name="storestatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "risk_level",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="risklevel",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("compliance_score", sa.Integer(), nullable=False),
        sa.Column("open_violation_count", sa.Integer(), nullable=False),
        sa.Column("opened_on", sa.Date(), nullable=True),
        sa.Column("last_inspection_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_inspection_due", sa.Date(), nullable=True),
        sa.Column("manager_id", sa.String(length=36), nullable=True),
        sa.Column("owner_id", sa.String(length=36), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["users.id"],
            name=op.f("fk_stores_manager_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_stores_owner_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stores")),
    )
    with op.batch_alter_table("stores", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_stores_code"), ["code"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_stores_manager_id"), ["manager_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stores_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_stores_region"), ["region"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_stores_risk_level"), ["risk_level"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_stores_status"), ["status"], unique=False)

    op.create_table(
        "inspections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("store_id", sa.String(length=36), nullable=False),
        sa.Column("inspector_id", sa.String(length=36), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "IN_PROGRESS",
                "ANALYZING",
                "COMPLETED",
                "CANCELLED",
                name="inspectionstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "method",
            sa.Enum(
                "AI_PHOTO",
                "AI_VIDEO",
                "ON_SITE",
                name="inspectionmethod",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "SCHEDULED",
                "AD_HOC",
                "COMPLAINT_FOLLOWUP",
                "REINSPECTION",
                name="inspectionsource",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checklist", sa.JSON(), nullable=False),
        sa.Column("complaint_text", sa.Text(), nullable=True),
        sa.Column("image_label", sa.String(length=160), nullable=True),
        sa.Column("frame_count", sa.Integer(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("risk_score", sa.Integer(), nullable=True),
        sa.Column(
            "risk_level",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="risklevel",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column("compliance_score", sa.Integer(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("model_version", sa.String(length=48), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["inspector_id"],
            ["users.id"],
            name=op.f("fk_inspections_inspector_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_inspections_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inspections")),
    )
    with op.batch_alter_table("inspections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_inspections_inspector_id"), ["inspector_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inspections_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inspections_store_id"), ["store_id"], unique=False
        )

    op.create_table(
        "ai_analyses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("inspection_id", sa.String(length=36), nullable=True),
        sa.Column("store_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                name="aianalysisstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model_version", sa.String(length=48), nullable=False),
        sa.Column("image_label", sa.String(length=160), nullable=True),
        sa.Column("frame_count", sa.Integer(), nullable=False),
        sa.Column("risk_score", sa.Integer(), nullable=True),
        sa.Column(
            "risk_level",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="risklevel",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column("detections", sa.JSON(), nullable=False),
        sa.Column("headline", sa.Text(), nullable=True),
        sa.Column("narrative", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("requested_by_id", sa.String(length=36), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
            name=op.f("fk_ai_analyses_inspection_id_inspections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"],
            ["users.id"],
            name=op.f("fk_ai_analyses_requested_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_ai_analyses_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_analyses")),
    )
    with op.batch_alter_table("ai_analyses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ai_analyses_inspection_id"), ["inspection_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ai_analyses_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ai_analyses_store_id"), ["store_id"], unique=False
        )

    op.create_table(
        "complaints",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("store_id", sa.String(length=36), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "APP",
                "PHONE",
                "EMAIL",
                "WALK_IN",
                "SOCIAL",
                name="complaintchannel",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "TRIAGED",
                "INVESTIGATING",
                "RESOLVED",
                "DISMISSED",
                name="complaintstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "MINOR",
                "MAJOR",
                "CRITICAL",
                name="severity",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column("reporter_name", sa.String(length=160), nullable=True),
        sa.Column("reporter_contact", sa.String(length=255), nullable=True),
        sa.Column("subject", sa.String(length=200), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("triaged_by_id", sa.String(length=36), nullable=True),
        sa.Column("triaged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("linked_inspection_id", sa.String(length=36), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["linked_inspection_id"],
            ["inspections.id"],
            name=op.f("fk_complaints_linked_inspection_id_inspections"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_complaints_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["triaged_by_id"],
            ["users.id"],
            name=op.f("fk_complaints_triaged_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complaints")),
    )
    with op.batch_alter_table("complaints", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_complaints_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_complaints_store_id"), ["store_id"], unique=False
        )

    op.create_table(
        "reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("inspection_id", sa.String(length=36), nullable=False),
        sa.Column("store_id", sa.String(length=36), nullable=False),
        sa.Column("reference", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "FINAL", name="reportstatus", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column(
            "risk_level",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="risklevel",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("grade", sa.String(length=2), nullable=False),
        sa.Column("minor_count", sa.Integer(), nullable=False),
        sa.Column("major_count", sa.Integer(), nullable=False),
        sa.Column("critical_count", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("recommendations", sa.JSON(), nullable=False),
        sa.Column("timeline", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("inspector_name", sa.String(length=160), nullable=True),
        sa.Column("model_version", sa.String(length=48), nullable=True),
        sa.Column("generated_by_id", sa.String(length=36), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pdf_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("share_token", sa.String(length=64), nullable=True),
        sa.Column("shared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["generated_by_id"],
            ["users.id"],
            name=op.f("fk_reports_generated_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
            name=op.f("fk_reports_inspection_id_inspections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_reports_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reports_inspection_id"), ["inspection_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_reports_reference"), ["reference"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_reports_share_token"), ["share_token"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_reports_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_reports_store_id"), ["store_id"], unique=False
        )

    op.create_table(
        "violations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("inspection_id", sa.String(length=36), nullable=True),
        sa.Column("store_id", sa.String(length=36), nullable=False),
        sa.Column("type_code", sa.String(length=48), nullable=False),
        sa.Column("label", sa.String(length=160), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "MINOR",
                "MAJOR",
                "CRITICAL",
                name="severity",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "IN_REMEDIATION",
                "RESOLVED",
                "WAIVED",
                name="violationstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("bounding_box", sa.JSON(), nullable=True),
        sa.Column("standard_ref", sa.String(length=120), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("remediation", sa.Text(), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by_id", sa.String(length=36), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
            name=op.f("fk_violations_inspection_id_inspections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_id"],
            ["users.id"],
            name=op.f("fk_violations_resolved_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_violations_store_id_stores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_violations")),
    )
    with op.batch_alter_table("violations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_violations_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_violations_inspection_id"), ["inspection_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_violations_severity"), ["severity"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_violations_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_violations_store_id"), ["store_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_violations_type_code"), ["type_code"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("violations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_violations_type_code"))
        batch_op.drop_index(batch_op.f("ix_violations_store_id"))
        batch_op.drop_index(batch_op.f("ix_violations_status"))
        batch_op.drop_index(batch_op.f("ix_violations_severity"))
        batch_op.drop_index(batch_op.f("ix_violations_inspection_id"))
        batch_op.drop_index(batch_op.f("ix_violations_category"))

    op.drop_table("violations")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_store_id"))
        batch_op.drop_index(batch_op.f("ix_reports_status"))
        batch_op.drop_index(batch_op.f("ix_reports_share_token"))
        batch_op.drop_index(batch_op.f("ix_reports_reference"))
        batch_op.drop_index(batch_op.f("ix_reports_inspection_id"))

    op.drop_table("reports")
    with op.batch_alter_table("complaints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_complaints_store_id"))
        batch_op.drop_index(batch_op.f("ix_complaints_status"))

    op.drop_table("complaints")
    with op.batch_alter_table("ai_analyses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_analyses_store_id"))
        batch_op.drop_index(batch_op.f("ix_ai_analyses_status"))
        batch_op.drop_index(batch_op.f("ix_ai_analyses_inspection_id"))

    op.drop_table("ai_analyses")
    with op.batch_alter_table("inspections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inspections_store_id"))
        batch_op.drop_index(batch_op.f("ix_inspections_status"))
        batch_op.drop_index(batch_op.f("ix_inspections_inspector_id"))

    op.drop_table("inspections")
    with op.batch_alter_table("stores", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stores_status"))
        batch_op.drop_index(batch_op.f("ix_stores_risk_level"))
        batch_op.drop_index(batch_op.f("ix_stores_region"))
        batch_op.drop_index(batch_op.f("ix_stores_owner_id"))
        batch_op.drop_index(batch_op.f("ix_stores_manager_id"))
        batch_op.drop_index(batch_op.f("ix_stores_code"))

    op.drop_table("stores")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_role"))
        batch_op.drop_index(batch_op.f("ix_users_region"))
        batch_op.drop_index(batch_op.f("ix_users_external_subject"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
